# Generated by Django 3.2.3 on 2021-05-28 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('P95', 'Petrol P95'), ('P98', 'Petrol P98'), ('ON', 'Diesel')], max_length=10)),
                ('fuel_price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='StationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship', models.CharField(choices=[('dolnoslaskie', 'dolnoslaskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('lodzkie', 'lodzkie'), ('malopolskie', 'malopolskie'), ('mazowieckie', 'mazowieckie')], max_length=30)),
                ('location_name', models.CharField(max_length=20)),
                ('x_coordinate', models.FloatField()),
                ('y_coordinate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PetrolStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=30)),
                ('fuel', models.ManyToManyField(to='app.Fuel')),
                ('location', models.ManyToManyField(to='app.StationLocation')),
            ],
        ),
    ]
