# Generated by Django 3.2.3 on 2021-06-01 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuel_type', models.CharField(choices=[('P95', 'Petrol P95'), ('P98', 'Petrol P98'), ('ON', 'Diesel')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='StationLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voivodeship', models.CharField(choices=[('dolnoslaskie', 'dolnoslaskie'), ('kujawsko-pomorskie', 'kujawsko-pomorskie'), ('lubelskie', 'lubelskie'), ('lubuskie', 'lubuskie'), ('lodzkie', 'lodzkie'), ('malopolskie', 'malopolskie'), ('mazowieckie', 'mazowieckie')], max_length=30)),
                ('city_name', models.CharField(max_length=20)),
                ('street_name', models.CharField(blank=True, max_length=30)),
                ('x_coordinate', models.FloatField(blank=True, default=1)),
                ('y_coordinate', models.FloatField(blank=True, default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='prices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PetrolStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=30)),
                ('fuel', models.ManyToManyField(to='app.Fuel')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.stationlocation')),
            ],
        ),
        migrations.AddField(
            model_name='fuel',
            name='fuel_price_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.price'),
        ),
    ]
