# Generated by Django 3.2.3 on 2021-05-29 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_auto_20210528_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuel',
            name='fuel_price_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
