# Generated by Django 3.2.3 on 2021-06-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_petrolstation_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrolstation',
            name='fuel',
            field=models.ManyToManyField(default=None, to='app.Fuel'),
        ),
    ]
