# Generated by Django 3.2.3 on 2021-07-08 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_petrolstation_fuel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petrolstation',
            name='fuel',
            field=models.ManyToManyField(blank=True, default=None, to='app.Fuel'),
        ),
    ]
