# Generated by Django 3.2.3 on 2021-05-29 00:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20210529_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='stationlocation',
            name='x_coordinate',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='stationlocation',
            name='y_coordinate',
            field=models.FloatField(blank=True),
        ),
    ]
