# Generated by Django 3.2.3 on 2021-05-29 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210529_0257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stationlocation',
            name='x_coordinate',
            field=models.FloatField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='stationlocation',
            name='y_coordinate',
            field=models.FloatField(blank=True, default=1),
        ),
    ]
